# Java 17 이미지 사용
FROM bellsoft/liberica-openjdk-alpine:17

# 작업 디렉토리 설정
WORKDIR /app

# Gradle wrapper 및 프로젝트 소스 코드 복사
COPY . .

# gradlew 파일에 실행 권한 부여
RUN chmod +x ./gradlew

# Gradle 빌드 실행 (테스트 제외)
RUN ./gradlew build -x test

# 빌드된 JAR 파일 복사
COPY build/libs/*.jar app.jar

# 포트 설정
EXPOSE 8080

# 애플리케이션 실행
ENTRYPOINT ["java", "-jar", "/app.jar"]