name: CI/CD using Docker & Github Actions.

# 1. main 브랜치에 push 또는 PR 작업이 이루어질 경우 액션 실행
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# 2. 자바 설정
jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      # 3. gradle build로 빌드파일 생성
      - name: Build with Gradlee
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: 도커 빌더 생성 및 부팅
        uses: docker/setup-buildx-action@v2

      - name: 도커 허브에 로그인
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Docker Build
        run: |
          #<USER_ID>/<REPO>:<TAG>
          # Docker 이미지 빌드
          docker build -f dockerfile -t ${{ secrets.DOCKER_USERNAME }}/hanghae99:${{ secrets.DOCKER_IMAGENAME }} .
          docker build -f dockerfile-mysql -t ${{ secrets.DOCKER_USERNAME }}/hanghae99:${{ secrets.DOCKER_IMAGENAME }} .
          
      - name: Purge old Docker image
        uses: deliverybot/docker-hub-purge-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          repository: ${{ secrets.DOCKER_USERNAME }}/hanghae99
          tag: ${{ secrets.DOCKER_IMAGENAME }}

      - name: Docker Hub Push
        run: |
          # Docker Hub 에 push
          docker push ${{ secrets.DOCKER_USERNAME }}/hanghae99:${{ secrets.DOCKER_IMAGENAME }}

          
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_IMAGENAME: ${{ secrets.DOCKER_IMAGENAME }}
          MYSQL_URL: ${{ secrets.MYSQL_URL }}
          MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
